#!/bin/sh

start() {
    mkdir -p /etc/sudoers.d
    echo "scalerunner ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/scalerunner
    
    # wait a bit until dhcp gets ip
    TIMEOUT=0
    while [ "1" = "1" ] ; do
        END=`route -n | grep ^0.0.0.0 | tail -1 | wc -l`
        if [ "$END" = "1" ] ; then
           break
        else
           TIMEOUT=`expr $TIMEOUT + 1`
        fi
        if [ "$TIMEOUT" = "5" ] ; then
           break
        fi
        sleep 1
    done

    GCP=`dmesg | grep "Google Compute Engine" | grep "BIOS Google" | wc -l`

    echo "Detecting if we're running in GCP..."

    /usr/local/bin/prepare_disk.sh

    if [ "$GCP" = "1" ] ; then
        echo "GCP detected"
        
        hostname=`curl --silent 'http://169.254.169.254/computeMetadata/v1/instance/hostname' -H 'Metadata-Flavor: Google' --max-time 5 --retry 5 | cut -f 1 -d '.'`
        echo "Setting hostname to ${hostname}"
        hostname $hostname
    fi
    
    return 0
}

stop() {
    return 0
}

restart() {
    return 0
}

case "$1" in
  start|stop|restart)
         "$1";;
  reload)
         restart;;
  *)
         echo "Usage: $0 {start|stop|restart|reload}"
	 exit 1
esac
