#!/bin/sh

monitor_keys() {
    echo "Monitoring ssh keys for $1"
    wait="0"
    while [ true ] ; do
        TMP=`mktemp`
        touch /home/scalerunner/.ssh/authorized_keys_$1
        if [ "$wait" = "1" ]; then
            wait_str="?wait_for_change=true"
        fi
        curl --silent "http://169.254.169.254/computeMetadata/v1/$1/attributes/ssh-keys${wait_str}" -H 'Metadata-Flavor: Google' > $TMP
        cat $TMP | grep ^scalerunner: | cut -f 2- -d ':' > /home/scalerunner/.ssh/authorized_keys_$1
        rm $TMP

        cat /home/scalerunner/.ssh/authorized_keys_$1 > /home/scalerunner/.ssh/authorized_keys

        chown -R scalerunner:scalerunner /home/scalerunner/.ssh

        echo "New keys insterted"
        wait="1"
        sleep 1
    done
}


start() {
    mkdir -p /etc/sudoers.d
    echo "scalerunner ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/scalerunner
    
    # wait a bit until dhcp gets ip
    TIMEOUT=0
    while [ "1" = "1" ] ; do
        END=`route -n | grep ^0.0.0.0 | tail -1 | wc -l`
        if [ "$END" = "1" ] ; then
           break
        else
           TIMEOUT=`expr $TIMEOUT + 1`
        fi
        if [ "$TIMEOUT" = "5" ] ; then
           break
        fi
        sleep 1
    done

    GCP=`dmesg | grep "Google Compute Engine" | grep "BIOS Google" | wc -l`

    echo "Detecting if we're running in GCP..."

    /usr/local/bin/prepare_disk.sh

    if [ "$GCP" = "1" ] ; then
        echo "GCP detected"
        
        hostname=`curl --silent 'http://169.254.169.254/computeMetadata/v1/instance/hostname' -H 'Metadata-Flavor: Google' --max-time 5 --retry 10 --retry-all-errors | cut -f 1 -d '.'`
        echo "Setting hostname to ${hostname}"
        hostname $hostname
        monitor_keys "instance" &
    fi
    
    return 0
}

stop() {
    return 0
}

restart() {
    return 0
}

case "$1" in
  start|stop|restart)
         "$1";;
  reload)
         restart;;
  *)
         echo "Usage: $0 {start|stop|restart|reload}"
	 exit 1
esac
