name: Build worker image
on: push

jobs:
  build_image:
    runs-on: [self-hosted, Linux, X64, cross-test]
    container: debian:bullseye
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install utils
        run: |
          echo "test"
          sleep 5s

      - name: Make Buildroot image
        run: |
          echo "end"

  second-job:
    runs-on: [self-hosted, Linux, X64, cross-test]
    container: debian:bullseye
    steps:
      - name: Test
        run: |
          echo "test"
          sleep 5s

      - name: End
        run: |
          echo "end"
